### ISSUE TITLE
NoClassDefFoundError when running the JAR

### ISSUE THREAD

**Issue by damianhinch** [teachthenet/TeachCraft-Challenges#4]
I get the following errors when I run the JAR with:

``` bash
java -jar Minecraft_Launcher.jar
```

``` bash
> java.lang.NoClassDefFoundError: javafx/embed/swing/JFXPanel
>   at java.lang.ClassLoader.defineClass1(Native Method)
>   at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
>   at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
>   at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
>   at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
>   at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
>   at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
>   at java.security.AccessController.doPrivileged(Native Method)
>   at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
>   at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
>   at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
>   at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
>   at ru.turikhay.tlauncher.rmo.TLauncher.<init>(TLauncher.java:185)
>   at ru.turikhay.tlauncher.rmo.TLauncher.launch(TLauncher.java:570)
>   at ru.turikhay.tlauncher.rmo.TLauncher.main(TLauncher.java:492)
> Caused by: java.lang.ClassNotFoundException: javafx.embed.swing.JFXPanel
>   at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
>   at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
>   at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
>   at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
>   ... 15 more
```

Machine info: Linux 3.19.0-58-generic x64, Java 1.8.0_45-internal, 15950 MB RAM

**Comment by njames** [comment]
I got a similar error but when I updated to the most recent java via http://www.webupd8.org/2012/09/install-oracle-java-8-in-ubuntu-via-ppa.html it launched fine.

```
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)
```

**Comment by damianhinch** [comment]
That fixed it, thanks!
